### ISSUE TITLE
CI Cleanup

### ISSUE THREAD

**Issue by alex404** [berenslab/retinal-rl#14]
Improve some of the CI structure.

- [x] Loosen strictness of pylinting so we can actually pass the checks.
  - [x] Unify local and CI linting rules 
- [x] Externalize run commands in workflows into locally runable scripts.
- [x] Maybe add some documentation somewhere about how the container can be pulled and tests can be run locally.
- [x] remove (or improve) caching, as pulling the container is fast enough and the overhead of the caching operation (if cache is not hit) is way larger
  - [x] make cache available in master branch
  - [x] find solution for case when def file is updated (cache inconsistency / public "main" def file can not be used)
- [x] remove login when pulling container

**Comment by fabioseel** [comment]
- [ ] remove (or improve) caching, as pulling the container is fast enough and the overhead of the caching operation (if cache is not hit) is way larger

**Comment by alex404** [comment]
Maybe instead of pylint we can use ruff and just based it off of the shared toml file? Pylint does more stuff, but I'm not sure if it does anything we really need. Regardless, we should have it set up so that our IDEs report to us errors that will trigger failures during CI.
