### ISSUE TITLE
Update README.md and Wiki

### ISSUE THREAD

**Issue by fabioseel** [berenslab/retinal-rl#18]
Both is quite out of date and could need an update soon!

In particular, it would be nice to
- [ ] have a section on the config system and how to setup an experiment
- [ ] add information on wandb usage and setup

**Comment by alex404** [comment]
I'll do this after I'm done with my current branch

**Comment by alex404** [comment]
I also think we'll just label the wiki as an archive. There's still tidbits of information, so I don't want to delete it, but yah. Just getting a decent readme will be enough for now.
